name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip python3-setuptools git zip openjdk-17-jdk

      - name: Install python-for-android
        run: |
          pip install python-for-android cython

      - name: Build APK with python-for-android
        run: |
          mkdir dist
          p4a apk \
            --private . \
            --package=hu.szotanulo.ultra \
            --name "SzotanuloUltra" \
            --version 1.0 \
            --bootstrap=sdl2 \
            --requirements=python3,kivy \
            --dist_name szotanulo \
            --arch armeabi-v7a \
            --sdk-dir $HOME/.local/share/python-for-android/android-sdk \
            --ndk-dir $HOME/.local/share/python-for-android/android-ndk \
            --android-api 27 \
            --ndk-api 21

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SzotanuloUltra.apk
          path: "**/*.apk"
