name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip python3-setuptools git zip
          pip install buildozer cython

      - name: Accept Android SDK licenses
        run: yes | /home/runner/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Build APK
        run: |
          buildozer init
          sed -i 's/title = .*/title = SzotanuloUltra/' buildozer.spec
          sed -i 's/source.include_exts = .*/source.include_exts = py,csv,json/' buildozer.spec
          sed -i 's/requirements = .*/requirements = python3,kivy/' buildozer.spec
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SzotanuloUltra.apk
          path: bin/*.apk
